eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9090
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: firstModule
        uri: lb://SERVICE-ONE
        predicates:
        - Path=/service1/**
      - id: secondModule
        uri: lb://SERVICE-TWO
        predicates:
        - Path=/service2/**